// <auto-generated />
using System;
using MU5PrototypeProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MU5PrototypeProject.Data.MUMigrations
{
    [DbContext(typeof(MUContext))]
    [Migration("20260418021531_MakeSessionClientSessionsPerWeekNullable")]
    partial class MakeSessionClientSessionsPerWeekNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("MU5PrototypeProject.Models.Accessories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearBar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadPad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeadRest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PosturePillow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RubberPads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionClientID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpringID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopperSettings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrapsOrHandles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Towel")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionClientID")
                        .IsUnique();

                    b.HasIndex("SpringID");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Action", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionClientID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Springs")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("SessionClientID");

                    b.ToTable("SessionExercises", (string)null);
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.AdminComplete", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminInitials")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionClientID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionClientID")
                        .IsUnique();

                    b.ToTable("AdminCompletes");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Apparatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApparatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Apparatuses");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientFolderUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApparatusID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApparatusID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseProp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ActionID");

                    b.HasIndex("PropID");

                    b.ToTable("ExerciseProps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.NextSteps", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CommunicatedProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CourseCorrectionNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NextAppointmentBooked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyToProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferredExternally")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferredTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionClientID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TeamConsult")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionClientID")
                        .IsUnique();

                    b.ToTable("NextSteps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.PhysioInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountUsed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CommunicatedWithPhysio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CoverageAmountPerYear")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CoverageResetsDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoverageShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsuranceCompany")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysioAssessment")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysiotherapistName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("PhysioInfos");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Prop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Props");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanceledBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionClient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionsPerWeekRecommended")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("SessionID", "ClientID")
                        .IsUnique();

                    b.HasIndex("SessionID", "ParticipantOrder")
                        .IsUnique();

                    b.ToTable("SessionClients");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionNotes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletedByTrainerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneralComments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectiveFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionClientID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectiveReports")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompletedByTrainerID");

                    b.HasIndex("SessionClientID")
                        .IsUnique();

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Spring", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparatusID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpringName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TensionLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApparatusID");

                    b.ToTable("Springs");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Trainer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Accessories", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.SessionClient", "SessionClient")
                        .WithOne("Accessories")
                        .HasForeignKey("MU5PrototypeProject.Models.Accessories", "SessionClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Spring", "Spring")
                        .WithMany("Accessories")
                        .HasForeignKey("SpringID");

                    b.Navigation("SessionClient");

                    b.Navigation("Spring");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Action", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Exercise", "Exercise")
                        .WithMany("Actions")
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.SessionClient", "SessionClient")
                        .WithMany("Actions")
                        .HasForeignKey("SessionClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("SessionClient");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.AdminComplete", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.SessionClient", "SessionClient")
                        .WithOne("AdminComplete")
                        .HasForeignKey("MU5PrototypeProject.Models.AdminComplete", "SessionClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionClient");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Apparatus", "Apparatus")
                        .WithMany("Exercises")
                        .HasForeignKey("ApparatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseProp", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Action", "Action")
                        .WithMany("ExerciseProps")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Prop", "Prop")
                        .WithMany("ExerciseProps")
                        .HasForeignKey("PropID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Prop");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.NextSteps", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.SessionClient", "SessionClient")
                        .WithOne("NextSteps")
                        .HasForeignKey("MU5PrototypeProject.Models.NextSteps", "SessionClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionClient");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.PhysioInfo", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithOne("PhysioInfo")
                        .HasForeignKey("MU5PrototypeProject.Models.PhysioInfo", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionClient", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Client", "Client")
                        .WithMany("SessionClients")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithMany("SessionClients")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionNotes", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Trainer", "CompletedByTrainer")
                        .WithMany()
                        .HasForeignKey("CompletedByTrainerID");

                    b.HasOne("MU5PrototypeProject.Models.SessionClient", "SessionClient")
                        .WithOne("SessionNotes")
                        .HasForeignKey("MU5PrototypeProject.Models.SessionNotes", "SessionClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByTrainer");

                    b.Navigation("SessionClient");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Spring", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Apparatus", "Apparatus")
                        .WithMany("Springs")
                        .HasForeignKey("ApparatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Action", b =>
                {
                    b.Navigation("ExerciseProps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Apparatus", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Springs");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Client", b =>
                {
                    b.Navigation("SessionClients");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Prop", b =>
                {
                    b.Navigation("ExerciseProps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.Navigation("PhysioInfo");

                    b.Navigation("SessionClients");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionClient", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Actions");

                    b.Navigation("AdminComplete");

                    b.Navigation("NextSteps");

                    b.Navigation("SessionNotes");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Spring", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Trainer", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
